update "Protection Against Bufferbloat"
ietf-wg-ccwg/rfc5033bis pull request #107
Opened 2024-04-01 15:18 UTC by nealcardwell

Tighten up the text and add some references.
cc: @mattmathis @martinduke @gorryfair @huitema

2024-04-01 16:49 UTC, martinduke requested changes
Most of your proposed changes make this read much better. Thanks!

2024-04-01 19:39 UTC, nealcardwell commented on draft-ietf-ccwg-rfc5033bis.md
> +Explicit Congestion Notification (ECN) {{?RFC3168}},{{?RFC9332}}.
OK, thanks. Removed!

2024-04-01 19:39 UTC, nealcardwell commented on draft-ietf-ccwg-rfc5033bis.md
> +
OK, removed!

2024-04-01 20:05 UTC, martinduke approved these changes

2024-04-02 05:28 UTC, huitema approved these changes

2024-04-02 14:36 UTC, merged