Restore end of PR #57
ietf-wg-ccwg/rfc5033bis pull request #113
Opened 2024-04-04 07:46 UTC by gorryfair

Fixed an editorial problem resulting in removing the end of the sentence, which went on to say that you can't assume DSCP, etc. 
Also changed /many deployments/ to simply say this happens without saying it is often.

2024-04-04 13:27 UTC, gloinul requested changes
Otherwise looks good, and with change I would approve.

2024-04-04 13:27 UTC, gloinul commented on draft-ietf-ccwg-rfc5033bis.md
> +Real-time flows can directed into distinct
missing "be"?

2024-04-04 16:10 UTC, martinduke approved these changes

2024-04-04 16:10 UTC, martinduke commented on draft-ietf-ccwg-rfc5033bis.md
> +y---
```suggestion
---
```

2024-04-09 06:59 UTC, gloinul approved these changes

2024-04-09 15:16 UTC, merged