Attempt to address comments from Warren Kumari
ietf-wg-ccwg/rfc5033bis pull request #136
Opened 2024-08-07 07:08 UTC by gorryfair

Proposed resolutions

2024-08-07 14:39 UTC, martinduke requested changes

2024-08-07 14:39 UTC, martinduke commented on draft-ietf-ccwg-rfc5033bis.md
> +standards track. For example, section 12. of  RFC6928 provides
```suggestion
standards track. For example, section 12 of RFC6928 provides
```

2024-08-07 14:39 UTC, martinduke commented on draft-ietf-ccwg-rfc5033bis.md
> +standards track. For example, section 12. of  RFC6928 provides
Should this be an informational reference?

2024-08-07 14:39 UTC, martinduke commented on draft-ietf-ccwg-rfc5033bis.md
> +expected by the TCPM working group. Section 4 of RFC4614 provides other
4614 has been obsoleted by 7414, but the later document is not as careful about formal Experimental status as the earlier one, so maybe your choice to reference 4614 is right.

But maybe this should be a reference?

2024-08-07 14:39 UTC, martinduke commented on draft-ietf-ccwg-rfc5033bis.md
> +they bring to the IETF.
IMO this paragraph pins too much on the authors. "Authors are expected to evaluate..." and then the second sentence uses the passive voice. I would prefer a paragraph like so:

"Publication of a specification by the IETF requires a well-rounded evaluation of the pros and cons of an algorithm. Both the document authors and participants in an IETF Working Group can conduct parts of this evaluation."

That's all we need to say, but I wouldn't object to further advice saying that the more work the authors do, the more likely it is to progress.

2024-08-07 18:51 UTC, martinduke approved these changes

2024-08-08 03:22 UTC, huitema approved these changes
You could merge it as is, but I don't like the remaining passive form too much.

2024-08-08 03:22 UTC, huitema commented on draft-ietf-ccwg-rfc5033bis.md
> +
You made sure to use the active form in the previous sentence, and now we are back to passive. How about:

A working group is expected to perform a well-rounded evaluation of the pros and cons of an algorithm
before it submits the specification for publication by the IETF.

2024-08-14 20:42 UTC, merged